"""DEEP16 build: write deep16/js/palette.js from deep16/palette.json, and deep16/data/sprites.js from the sprite sheets'
frame maps (deep16/art/*.json, written by tools/pixelate.py), then stamp ?v=<hash> on deep16/index.html's script tags.
Run: python tools/deep16-build.py"""
import hashlib, json, os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D16 = os.path.join(ROOT, 'deep16')


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def main():
    pal = json.load(open(os.path.join(D16, 'palette.json'), encoding='utf-8'))
    write(os.path.join(D16, 'js', 'palette.js'),
          "/* generated by tools/deep16-build.py from deep16/palette.json -- edit the JSON, not this */\n"
          "'use strict';\n(window.D16 = window.D16 || {}).PAL = " + json.dumps({'ramps': pal['ramps']}) + ";\n")

    sheets = {}
    for fn in sorted(glob.glob(os.path.join(D16, 'art', '*.json'))):
        meta = json.load(open(fn, encoding='utf-8'))
        # cache-bust the sheet image too (09-28: a sheet that gains an anim, the campfire's `sit`, must not be read from a
        # browser's older copy of the png)
        png = os.path.join(D16, meta['image'].split('?')[0])
        if os.path.exists(png):
            meta['image'] = meta['image'].split('?')[0] + '?v=' + hashlib.sha1(open(png, 'rb').read()).hexdigest()[:10]
        sheets[os.path.splitext(os.path.basename(fn))[0]] = meta
    write(os.path.join(D16, 'data', 'sprites.js'),
          "/* generated by tools/deep16-build.py from deep16/art/*.json (the frame maps tools/pixelate.py writes) */\n"
          "'use strict';\n(window.D16 = window.D16 || {}).SHEETS = " + json.dumps(sheets, indent=0) + ";\n")

    # cache-bust: ?v=<content hash> on every local script tag
    idx = os.path.join(D16, 'index.html')
    html = open(idx, encoding='utf-8').read()

    def stamp(m):
        src = m.group(1).split('?')[0]
        p = os.path.normpath(os.path.join(D16, src))
        if not os.path.exists(p):
            print('  missing script', src)
            return m.group(0)
        h = hashlib.sha1(open(p, 'rb').read()).hexdigest()[:10]
        return '<script src="%s?v=%s"></script>' % (src, h)
    html2 = re.sub(r'<script src="([^"]+)"></script>', stamp, html)
    if html2 != html:
        write(idx, html2)
    print('deep16: palette %d colours, %d sheets' % (sum(len(r) for r in pal['ramps'].values()), len(sheets)))


if __name__ == '__main__':
    main()
