"""DEEP16 pipeline 2 (generated art): the Wet's deep station -- its crate, its bucket and its lamp on a post -- from Griz's one sheet ->
wetcrate_p1, wetbucket_p1 and wetlamp_p1.

    python tools/wetprops-sheet.py           (all three; `check` also writes dev/visions/wetprops-check.png, the frames at 4x)

Source (gitignored, deep16/_src/): "Props_TheWet_GPT.png" -- Griz, 2026-10-08, from the paste in deep16-art-wanted.md "Props wanted"
(PROPS, THE DEEP STATION; his 10-06 ear file: "All 3 are very very 2D, particularly the lantern"). The bestiary lane, eyes-wetlamp.

The sheet is six drawings on a flat navy, no lettering: the crate and the bucket along the top, the lamp on its post four times along the
bottom (the flame in four shapes). Each is one blob (tools/sheetrows.py figure_mask); the lamp's four are laid on one another by the
post's foot (each blob's left edge and its lowest row: the post does not move, only the flame does).

Sizes (the seat's, against the grid's 64 x 32 floor diamond and a standing hero about 51 px tall): the crate about 38 px across, most of
its square, and short enough that a hero who walks onto its square for the bucket still reads beside it; the bucket about 19 px across,
the handle's loop in that; the post as tall as a standing man, about 50 px. GPT drew the three at no one scale, so each has its own.

Anchors (ax, ay): the crate's and the bucket's are the middle of the square they stand on -- the drawing's middle across, a quarter of
its width up from its lowest point (tools/gsprops-sheet.py); the lamp's is the post's foot, the middle of the post where it meets the
floor (the lantern hangs off to the right, over the square beside). The crate's json also carries `lift`: px up from its anchor to the
middle of its top, where the bucket sits while it lies on it (deep16/js/wet.js).
"""
import os, sys, json
import importlib.util
import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path); mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    return mod
GS = _load('gsprops', os.path.join(ROOT, 'tools', 'gsprops-sheet.py'))      # game(), lay(), write(), src(): the chest's and the cot's
SR = GS.SR
pix = GS.pix

SHEET = 'Props_TheWet_GPT.png'
GS.FPS.update({'crate': 1, 'bucket': 1, 'lit': 6})
W_CRATE, W_BUCKET, H_LAMP = 38.0, 19.0, 50.0
SRC = 'generated by Griz (2026-10-08, one sheet from the paste in deep16-art-wanted.md "Props wanted"), cut by tools/wetprops-sheet.py'


def blobs():
    """the six drawings: [(rgba array, box x0 y0 x1 y1)] -- the crate, the bucket, then the four lamps left to right"""
    a = np.asarray(Image.open(GS.src(SHEET)).convert('RGB')).astype(np.int32)
    m = SR.figure_mask(a)
    lab, n = ndimage.label(m, structure=np.ones((3, 3)))
    sz = ndimage.sum(m, lab, range(1, n + 1))
    big = 1 + np.argsort(sz)[::-1][:6]
    sl = ndimage.find_objects(lab)
    big = sorted(big, key=lambda i: (sl[i - 1][0].start > 420, sl[i - 1][1].start))   # the top row first, then left to right
    out = []
    for i in big:
        im, box = SR.rgba_crop(a, lab == i)
        out.append((np.asarray(im), box))
    return out


def lamp_anchor(c):
    """the post's foot in a game-size cell: the columns of its lowest rows (only the post reaches the floor), their middle across, and a
    quarter of the post's width up from its lowest point"""
    al = c[..., 3] > 0
    ys = np.where(al.any(1))[0]
    foot = al[ys[-1] - 2:ys[-1] + 1].any(0)
    xs = np.where(foot)[0]
    w = xs.max() - xs.min() + 1
    return int(round((xs.min() + xs.max()) / 2)), int(round(ys[-1] - w / 4))


def main():
    (crate, cbox), (bucket, bbox), *lamps = blobs()
    sheets = []

    cells, fw, fh, ax, ay = GS.lay([('crate', crate, (0, 0))], (cbox[2] - cbox[0] - 4) / W_CRATE)
    al = cells[0][1][..., 3] > 0
    ys, xs = np.where(al)
    lift = int(round(ay - (ys.min() + (xs.max() - xs.min() + 1) / 4)))
    sheets.append(GS.write('wetcrate_p1', [('crate', [cells[0][1]])], fw, fh, ax, ay,
        'the Wet\'s deep station crate (tools/wetprops-sheet.py): a plain wooden crate, a nailed cross on its two sides, in the grid\'s view. '
        '(ax, ay) is the middle of the square it stands on; `lift` is px up from there to the middle of its top, where the bucket sits.', SRC))
    j = os.path.join(pix.ART, 'wetcrate_p1.json'); meta = json.load(open(j, encoding='utf-8')); meta['lift'] = lift
    json.dump(meta, open(j, 'w', encoding='utf-8'), indent=1)
    print('  wetcrate_p1 lift', lift)

    cells, fw, fh, ax, ay = GS.lay([('bucket', bucket, (0, 0))], (bbox[2] - bbox[0] - 4) / W_BUCKET)
    sheets.append(GS.write('wetbucket_p1', [('bucket', [cells[0][1]])], fw, fh, ax, ay,
        'the Wet\'s deep station bucket (tools/wetprops-sheet.py): wooden staves, two iron hoops, a rope handle, its mouth open and dark. '
        '(ax, ay) is the middle of the square it stands on.', SRC))

    k = max(b[3] - b[1] - 4 for _, b in lamps) / H_LAMP
    # on one another by the left edge and the foot: each crop's top left at x 0, its bottom row on y 0
    cells, fw, fh, _, _ = GS.lay([('lit%d' % (i + 1), im, (0, -im.shape[0])) for i, (im, b) in enumerate(lamps)], k)
    ax, ay = lamp_anchor(cells[0][1])
    sheets.append(GS.write('wetlamp_p1', [('lit', [c for _, c in cells])], fw, fh, ax, ay,
        'the Wet\'s deep station lamp (tools/wetprops-sheet.py): an iron cage lantern hung from the arm of a wooden post, lit; lit, four '
        'frames of its flame. (ax, ay) is the post\'s foot on the square it stands on; the lantern hangs over the square to its right on '
        'the screen.', SRC))

    if 'check' in sys.argv[1:]:
        h = sum(s.shape[0] for s in sheets) + 16
        w = max(s.shape[1] for s in sheets)
        canvas = Image.new('RGBA', (w, h), (40, 44, 60, 255))
        y = 0
        for s in sheets:
            canvas.alpha_composite(Image.fromarray(s, 'RGBA'), (0, y)); y += s.shape[0] + 8
        out = os.path.join(ROOT, 'dev', 'visions', 'wetprops-check.png')
        os.makedirs(os.path.dirname(out), exist_ok=True)
        canvas.resize((w * 4, h * 4), Image.NEAREST).save(out)
        print('check:', out)


if __name__ == '__main__':
    main()
